repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    - id: check-merge-conflict
    - id: check-added-large-files
      maxkb: 8192
    - id: check-xml
    - id: end-of-file-fixer
    - id: trailing-whitespace

  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
      - id: flake8
