title = "NuSpaceSim"

[detector]
name = "Default Name"

[detector.initial_position]
altitude = "525.0 km"
latitude = "0.0 deg"
longitude = "0.0 deg"

[detector.flight]
id = "stationary"
duration = "86400.0 s"
start_date = "2022-06-02T01:00:00"
start_date_format = "isot"

[detector.field_of_view]
nadir_span = "7.0 deg"
azimuth_span = "360.0 deg"

[detector.pointing]
id = "from_limb"
nadir_center_wrt_limb = "-3.5 deg"
azimuth_center = "0.0 deg"

[detector.sun_moon]
id = "apply_sun_moon_cuts"
sun_alt_cut = "-40.5 deg"
moon_alt_cut = "0.0 deg"
moon_min_phase_angle_cut = "150.0 deg"

[detector.optical]
enable = true
telescope_effective_area = "2.5 m2"
quantum_efficiency = 0.2
photo_electron_threshold = 10
duty_cycle = 0.2

[detector.radio]
enable = true
low_frequency = "30.0 MHz"
high_frequency = "300.0 MHz"
snr_threshold = 5.0
nantennas = 10
gain = "1.8 dB"

[simulation]
mode = "Target"
num_time_bins = 1000
max_cherenkov_angle = "3.0000000000000004 deg"
eas_long_profile = "Greisen"
use_refactored_photon_sum = false
refactored_photon_sum_variant = "v2"
cherenkov_light_engine = "nuspacesim"

[simulation.integ_method]
id = "target_approx"

[simulation.ionosphere]
enable = true
total_electron_content = 10.0
total_electron_error = 0.1

[simulation.cherenkov_quadrature]
n_nodes = 12
n_slant_sub = 8
n_energy_low = 3
n_energy_high = 8

[simulation.tau_shower]
id = "nupyprop"
etau_frac = 0.5
table_version = "3"

[simulation.spectrum]
id = "monospectrum"
log_nu_energy = 8.0

[simulation.cloud_model]
id = "no_cloud"

[simulation.target]
id = "single_pt_source"
source_RA = "0.0 deg"
source_DEC = "0.0 deg"
source_date = "2022-06-02T01:00:00"
source_date_format = "isot"
source_obst = "86400.0 s"
