name: PyPI 🐍  Wheel 🎡

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:

  build_wheels:
    name: Build wheel for cp${{ matrix.python }}-${{ matrix.platform_id }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest]
        python: [39, 310, 311, 312, 313]
        arch: [x86, arm]
        include:
          - os: ubuntu-latest
            arch: x86
            platform_id: manylinux_x86_64
            cibw_arch: auto
          - os: macos-latest
            arch: x86
            platform_id: macosx_x86_64
            cibw_arch: x86_64
          - os: macos-latest
            arch: arm
            platform_id: macosx_arm64
            cibw_arch: arm64
        exclude:
          - os: ubuntu-latest
            arch: arm

    steps:
    - uses: actions/checkout@v3
    - name: Get history and tags for SCM versioning
      run: |
        git fetch --prune --unshallow
        git fetch --depth=1 origin +refs/tags/*:refs/tags/*

    - name: Build wheels
      uses: pypa/cibuildwheel@v2.22.0
      env:
        CIBW_BUILD: cp${{ matrix.python }}-${{ matrix.platform_id }}
        CIBW_ARCHS_LINUX: ${{ matrix.cibw_arch }}
        CIBW_ARCHS_MACOS: ${{ matrix.cibw_arch }}
        CIBW_TEST_SKIP: "*_aarch64, *macosx*, *_arm64, *_universal2:arm64"

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: nuspacesim-gh-pypi-artifact-${{ matrix.os }}-${{ matrix.cibw_arch }}-cp${{ matrix.python }}-${{ github.run_id }}
        path: wheelhouse/*.whl
        retention-days: 1

  publish:
    name: Publish wheels to PyPI
    runs-on: ubuntu-latest
    needs: build_wheels

    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest]
        python: [39, 310, 311, 312, 313]
        arch: [x86, arm]
        include:
          - os: ubuntu-latest
            arch: x86
            platform_id: manylinux_x86_64
            cibw_arch: auto
          - os: macos-latest
            arch: x86
            platform_id: macosx_x86_64
            cibw_arch: x86_64
          - os: macos-latest
            arch: arm
            platform_id: macosx_arm64
            cibw_arch: arm64
        exclude:
          - os: ubuntu-latest
            arch: arm

    steps:
    - name: Download Build Artifacts
      uses: actions/download-artifact@v4
      with:
        name: nuspacesim-gh-pypi-artifact-${{ matrix.os }}-${{ matrix.cibw_arch }}-cp${{ matrix.python }}-${{ github.run_id }}
        path: wheelhouse/

    - name: Publish a Python distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_SECRET }}
        packages_dir: wheelhouse/
