name: CI/CD 📝

on:
  schedule:
    - cron: "55 4 * * *"
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'test/**'
      - setup.py
      - setup.cfg
      - pyproject.toml
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:

  build_wheels:
    name: Build wheel for cp${{ matrix.python }}-${{ matrix.platform_id }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        os:
          - linux_x86_64
          - linux_aarch64
          - linux_ppc64le
          - macosx_x86_64
          - macosx_arm64
          - macosx_universal2
        python: [38, 39, 310, 311, 312]
        include:
          - os: linux_x86_64
            platform_id: manylinux_x86_64
          - os: linux_aarch64
            platform_id: manylinux_aarch64
          - os: linux_ppc64le
            platform_id: manylinux_ppc64le
          - os: macosx_x86_64
            platform_id: macosx_x86_64
          - os: macosx_arm64
            platform_id: macosx_arm64
          - os: macosx_universal2
            platform_id: macosx_universal2

    steps:
    - uses: actions/checkout@v3
    - name: Get history and tags for SCM versioning
      run: |
        git fetch --prune --unshallow
        git fetch --depth=1 origin +refs/tags/*:refs/tags/*

    - name: Build wheels
      uses: pypa/cibuildwheel@v2.15.0
      env:
        CIBW_BUILD: cp${{ matrix.python }}-${{ matrix.platform_id }}
        # CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: nuspacesim-gh-pypi-artifact
        path: wheelhouse/*.whl
        retention-days: 1
