name: CI/CD 📝

on:
  schedule:
    - cron: "55 4 * * *"
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'test/**'
      - setup.py
      - setup.cfg
      - pyproject.toml
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:

  build_wheels:
    name: Wheel cp${{ matrix.python }}-${{ matrix.platform }}_${{ matrix.arch }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64]
        os: [ubuntu-latest, macos-latest]
        python: [38, 39, 310, 311, 312]
        include:
          - os: ubuntu-latest
            platform: manylinux
            arch: aarch64
            arch: ppc64le
          - os: macos-latest
            platform: macosx
            arch: arm64
            arch: universal2

    steps:
    - uses: actions/checkout@v3
    - name: Get history and tags for SCM versioning
      run: |
        git fetch --prune --unshallow
        git fetch --depth=1 origin +refs/tags/*:refs/tags/*

    - name: Build wheels
      uses: pypa/cibuildwheel@v2.15.0
      env:
        CIBW_BUILD: cp${{ matrix.python }}-${{ matrix.platform }}_${{ matrix.arch }}

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: nuspacesim-gh-pypi-artifact
        path: wheelhouse/*.whl
        retention-days: 1
