name: CI/CD 📝

on:
  schedule:
    - cron: "55 4 * * *"
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'test/**'
      - setup.py
      - setup.cfg
      - pyproject.toml
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:

  build_wheels:
    name: Build wheel for cp${{ matrix.python }}-${{ matrix.platform_id }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python: [37, 38, 39, 310, 311]
        include:
          - os: ubuntu-latest
            platform_id: manylinux_x86_64
          - os: macos-latest
            platform_id: macosx_x86_64

    steps:
    - uses: actions/checkout@v2
    - name: Get history and tags for SCM versioning
      run: |
        git fetch --prune --unshallow
        git fetch --depth=1 origin +refs/tags/*:refs/tags/*

    - name: Build wheels
      uses: pypa/cibuildwheel@v2.13.1
      env:
        CIBW_BUILD: cp${{ matrix.python }}-${{ matrix.platform_id }}
        CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: nuspacesim-gh-pypi-artifact
        path: wheelhouse/*.whl
        retention-days: 1
