name: CI/CD 📝

on:
  schedule:
    - cron: "55 4 * * *"
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'test/**'
      - setup.py
      - setup.cfg
      - pyproject.toml
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:

  build_wheels:
    name: Wheel cp${{ matrix.python }}-${{ matrix.os }}-${{ matrix.arch }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python: [310, 311]
        arch: [x86, arm]

    steps:
    - uses: actions/checkout@v3
    - name: Get history and tags for SCM versioning
      run: |
        git fetch --prune --unshallow
        git fetch --depth=1 origin +refs/tags/*:refs/tags/*

    - name: Set up QEMU for ARM on Linux
      if: matrix.arch == 'arm' && matrix.os == 'ubuntu-latest'
      uses: docker/setup-qemu-action@v2
      with:
        platforms: all

    - name: Set up environment vars
      run: |
        case ${{ matrix.os }} in 
          'ubuntu-latest') 
              ARCH=$([ ${{matrix.arch}} == 'arm' ] && echo 'aarch' || echo 'x86_')
              PFID="manylinux_${ARCH}"
          ;;
          'macos-latest')
              ARCH=$([ ${{matrix.arch}} == 'arm' ] && echo 'arm' || echo 'x86_')
              PFID="macosx_${ARCH}64"
          ;;
        esac
        export "PFID=$PFID"

    - name: Build wheels
      uses: pypa/cibuildwheel@v2.15.0
      env:
        CIBW_BUILD: cp${{ matrix.python }}-$PFID

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: nuspacesim-gh-pypi-artifact
        path: wheelhouse/*.whl
        retention-days: 1
